const FILTER = {
    // sort
    MOST_VIEWS: 'MOST_VIEWS',
    MOST_STARS: 'MOST_STARS',
    MOST_FAVORITES: 'MOST_FAVORITES',
    MOST_COMMENTS: 'MOST_COMMENTS',

    ASC_INSERTED: 'ASC_INSERTED',
    DESC_INSERTED: 'DESC_INSERTED',
    MOST_LIKES: 'MOST_LIKES',
    MOST_DISLIKES: 'MOST_DISLIKES',
};

export default FILTER;
